### ISSUE TITLE
ConfigMap path does not exists

### ISSUE THREAD

**Issue by christophlehmann** [ausov/k8s-mariadb-cluster#1]
Hi, I tried the setup with Kubernetes.

First issue is the path does not exists in https://github.com/ausov/k8s-mariadb-cluster/blob/7c772e2d32e742455a1f0a66bb99467d58b13cb7/example/galera.yaml#L84

Commenting it out, the first container starts and i only see `2017/08/26 00:34:51 lookup galera on 10.3.0.10:53: no such host`. Nothing happens after that, just as a note.

**Comment by neverfox** [comment]
Add it to the ConfigMap.

**Comment by jengo** [comment]
Thanks for posting a fix, I created a PR with it

**Comment by ausov** [comment]
Closed with #2
